forge 'https://forgeapi.puppetlabs.com'

moduledir '/etc/puppet/environments/production/modules'

mod 'puppetlabs/stdlib'
mod 'nanliu/staging'
mod 'puppetlabs/concat', '1.2.3'
mod 'puppetlabs/mysql', '3.4.0'
mod 'puppetlabs/apache'
