forge 'https://forgeapi.puppetlabs.com'

moduledir '/etc/puppet/environments/testing/modules'

mod 'puppetlabs/stdlib'
mod 'puppetlabs/ntp'
mod 'nanliu/staging'
mod 'puppetlabs/concat', '1.2.3'
mod 'puppetlabs/mysql', '3.4.0'
mod 'puppetlabs/apache', '1.5.0'
